-- 游戏配置表
INSERT INTO `game_config`(`config_type`, `config_sub_type`, `config_clazz`, `config_code`, `config_value`, `config_desc`)
VALUES
    ('server', 'CheatSystem', 'java.lang.Boolean', 'cheat_pet_itemvac_switch', 'true', 'cheat_pet_itemvac_switch'),
    ('server', 'CheatSystem', 'java.lang.Boolean', 'cheat_pet_itemvac_show_params', 'true', 'cheat_pet_itemvac_show_params'),
    ('server', 'CheatSystem', 'java.lang.Boolean', 'cheat_pet_itemvac_allow_in_event', 'false', 'cheat_pet_itemvac_allow_in_event'),
    ('server', 'CheatSystem', 'java.lang.Double', 'cheat_pet_itemvac_radius_max', '15000', 'cheat_pet_itemvac_radius_max'),
    ('server', 'CheatSystem', 'java.lang.Integer', 'cheat_pet_itemvac_sleep_min', '500', 'cheat_pet_itemvac_sleep_min'),
    ('server', 'CheatSystem', 'java.lang.Integer', 'cheat_pet_itemvac_sleep_max', '5000', 'cheat_pet_itemvac_sleep_max'),
    ('server', 'CheatSystem', 'java.lang.Boolean', 'cheat_pet_itemvac_radius_auto', 'true', 'cheat_pet_itemvac_radius_auto'),
    ('server', 'CheatSystem', 'java.lang.Integer', 'cheat_pet_itemvac_max_level', '20', 'cheat_pet_itemvac_max_level'),
    ('server', 'Safe', 'java.lang.Integer', 'ban_mac_ignore_majority', '5', 'ban_mac_ignore_majority'),
    ('server', 'Safe', 'java.lang.String', 'deterred_universal_client', '', 'deterred_universal_client'),
    ('server', 'Safe', 'java.lang.Integer', 'login_client_limit', '0', 'login_client_limit'),
    ('server', 'Safe', 'java.lang.Integer', 'login_client_limit_today', '0', 'login_client_limit_today'),
    ('server', 'Game Mechanics', 'java.lang.Boolean', 'allow_exp_multiplier_card', 'true', 'allow_exp_multiplier_card'),
    ('server', 'Game Mechanics', 'java.lang.Boolean', 'allow_drop_multiplier_card', 'true', 'allow_drop_multiplier_card'),
    ('server', 'Anti Cheat', 'java.lang.Boolean', 'anti_cheat_auto_detection', 'true', 'anti_cheat_auto_detection'),
    ('server', 'Anti Cheat', 'java.lang.Boolean', 'anti_cheat_auto_disconnect', 'true', 'anti_cheat_auto_disconnect'),
    ('server', 'Anti Cheat', 'java.lang.Boolean', 'anti_cheat_auto_losehpmp', 'false', 'anti_cheat_auto_losehpmp'),
    ('server', 'Anti Cheat', 'java.lang.Integer', 'anti_cheat_fast_attack_interval', '0', 'anti_cheat_fast_attack_interval');

-- 多语言资源表
INSERT INTO `lang_resources`(`lang_type`, `lang_base`, `lang_code`, `lang_value`)
VALUES
    ('zh-CN', 'game_config', 'cheat_pet_itemvac_switch', '宠物范围吸物开关'),
    ('en-US', 'game_config', 'cheat_pet_itemvac_switch', 'Pet Area Item Vacuum Switch'),
    ('zh-CN', 'game_config', 'cheat_pet_itemvac_allow_in_event', '是否允许在事件中使用宠吸 - 当事件存在BOSS，在击杀BOSS后30秒内无法使用宠吸 - true:允许,false:禁止'),
    ('en-US', 'game_config', 'cheat_pet_itemvac_allow_in_event', 'Allow pet vacuum in events - When boss exists in event, pet vacuum is disabled for 30 seconds after boss defeat - true:allow,false:forbid'),
    ('zh-CN', 'game_config', 'cheat_pet_itemvac_show_params', '显示宠吸参数提示 - 启用后会在宠吸启动时显示当前参数信息'),
    ('en-US', 'game_config', 'cheat_pet_itemvac_show_params', 'Show pet vacuum parameter hints - Displays current parameters when pet vacuum starts'),
    ('zh-CN', 'game_config', 'cheat_pet_itemvac_radius_max', '宠物拾取最大半径(码) - 默认15000'),
    ('en-US', 'game_config', 'cheat_pet_itemvac_radius_max', 'Pet pickup maximum radius(yards) - Default:15000'),
    ('zh-CN', 'game_config', 'cheat_pet_itemvac_sleep_min', '宠物拾取最小间隔(毫秒) - 最小值:200，默认500'),
    ('en-US', 'game_config', 'cheat_pet_itemvac_sleep_min', 'Pet pickup minimum interval(ms) - Minimum:200, Default:500'),
    ('zh-CN', 'game_config', 'cheat_pet_itemvac_sleep_max', '宠物拾取最大间隔(毫秒) - 默认5000(5秒)'),
    ('en-US', 'game_config', 'cheat_pet_itemvac_sleep_max', 'Pet pickup maximum interval(ms) - Default:5000(5 seconds)'),
    ('zh-CN', 'game_config', 'cheat_pet_itemvac_radius_auto', '自动计算拾取范围和间隔 - 根据宠物等级、饱食度、亲密度动态调整'),
    ('en-US', 'game_config', 'cheat_pet_itemvac_radius_auto', 'Auto-calculate pickup range and interval - Dynamically adjusts based on pet level, fullness, and intimacy'),
    ('zh-CN', 'game_config', 'cheat_pet_itemvac_max_level', '宠物自动拾取计算最高等级 - 范围:1~255，默认20级'),
    ('en-US', 'game_config', 'cheat_pet_itemvac_max_level', 'Pet auto-pickup calculation max level - Range:1~255, Default:20'),
    ('zh-CN', 'game_config', 'ban_mac_ignore_majority', '虚拟机MAC检测阈值 - 出现次数超过此值的MAC将被视为虚拟机MAC而不被封禁'),
    ('en-US', 'game_config', 'ban_mac_ignore_majority', 'VM MAC detection threshold - MAC addresses appearing more than this threshold will be treated as VM MACs and not banned'),
    ('zh-CN', 'game_config', 'deterred_universal_client', '客户端登录验证标识 - 用于防止万能客户端非法连接'),
    ('en-US', 'game_config', 'deterred_universal_client', 'Client login verification identifier - Prevents illegal connections from universal clients'),
    ('zh-CN', 'game_config', 'login_client_limit', '客户端登录数量限制 - 限制同一设备IP、MAC、HWID的最大同时登录数量，0为不限制'),
    ('en-US', 'game_config', 'login_client_limit', 'Client login limit - Limit the maximum number of simultaneous logins for the same device''s IP, MAC, and HWID, with 0 indicating no limit'),
    ('zh-CN', 'game_config', 'login_client_limit_today', '客户端登录数量限制(今天) - 限制同一设备今天的IP、MAC、HWID的累计登录数量上限，0为不限制'),
    ('en-US', 'game_config', 'login_client_limit_today', 'Client login limit (today) - Limit the cumulative login limit for the same device''s IP, MAC, and HWID today, with 0 indicating no limit'),
    ('zh-CN', 'game_config', 'allow_exp_multiplier_card', '允许使用经验倍率卡 - 控制背包里的倍率卡是否生效。（true:允许,false:禁止）'),
    ('en-US', 'game_config', 'allow_exp_multiplier_card', 'Allow using experience multiplier cards - Controls whether multiplier cards in inventory take effect. (true:allow,false:forbid)'),
    ('zh-CN', 'game_config', 'allow_drop_multiplier_card', '允许使用掉落倍率卡 - 控制背包里的倍率卡是否生效。（true:允许,false:禁止）'),
    ('en-US', 'game_config', 'allow_drop_multiplier_card', 'Allow using drop multiplier cards - Controls whether multiplier cards in inventory take effect. (true:allow,false:forbid)'),
    ('zh-CN', 'game_config', 'anti_cheat_auto_detection', '反作弊_自动检测 - 控制是否启用自动作弊检测功能'),
    ('en-US', 'game_config', 'anti_cheat_auto_detection', 'Anti-Cheat Auto Detection - Controls whether to enable automatic cheat detection'),
    ('zh-CN', 'game_config', 'anti_cheat_auto_disconnect', '反作弊_自动断开 - 部分功能检测到作弊超过阈值时自动断开玩家连接，如开启自动封号则优先封号'),
    ('en-US', 'game_config', 'anti_cheat_auto_disconnect', 'Anti cheating automatic disconnection - Some functions automatically disconnect players when cheating exceeds the threshold'),
    ('zh-CN', 'game_config', 'anti_cheat_auto_losehpmp', '反作弊_惩罚扣血扣蓝 - 部分功能检测到作弊的玩家自动被扣血扣篮以示惩罚，如开启自动封号则优先封号'),
    ('en-US', 'game_config', 'anti_cheat_auto_losehpmp', 'Anti-Cheat Penalty: Auto Lose HP/MP - Players detected cheating will automatically lose HP and MP as a penalty'),
    ('zh-CN', 'game_config', 'anti_cheat_fast_attack_interval', '快速攻击检测间隔(毫秒) - 检测玩家攻击频率，0为关闭此功能，一般建议在200ms~300ms，如经常误判，则自行调低。'),
    ('en-US', 'game_config', 'anti_cheat_fast_attack_interval', 'Fast Attack Detection Interval(ms) - Detects player attack frequency, 0 to disable this feature.It is recommended to adjust it within 200ms~300ms. If there are frequent misjudgments, adjust it accordingly.');
